[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "furo"
dynamic = ["version", "description"]
readme = "README.md"

requires-python = ">=3.6"
dependencies = [
  "beautifulsoup4",
  "sphinx ~= 4.0",
]

authors = [
    {name = "Pradyun Gedam", email = "mail@pradyunsg.me"},
]
classifiers = [
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: MIT License",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Operating System :: OS Independent",
  "Topic :: Documentation",
  "Topic :: Software Development :: Documentation",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
  "pytest-xdist",
]
doc = [
  "myst-parser",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinx-inline-tabs",
]

[project.entry-points]
"sphinx.html_themes" = {furo = "furo"}

[tool.flit.sdist]
include = [
  # Generated assets
  "src/furo/theme/furo/static/*/*",
]
exclude = [
  "docs/", "src/furo/assets",
  # JS stuff
  "gulpfile.js", "package.json", "package-lock.json",
  # Linting stuff
  ".flake8", ".isort.cfg", ".pre-commit-config.yaml",
]
