blank_issues_enabled: false
contact_links:
  - name: Potential Issue
    url: https://github.com/pradyunsg/furo/discussions/categories/potential-issue
    about: Possible bugs may be raised as a "Potential Issue" discussion.
  - name: Ideas
    url: https://github.com/pradyunsg/furo/discussions/categories/ideas
    about: Feature requests may be raised as an "Ideas" discussion.
