name: Deploy
on:
  push:
    branches: [master]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        pip install nox
        npm install

    - name: Generate documentation
      run: nox -s docs

    # This helps ensure the generated files are included by the action
    # in the next step.
    - name: Remove generated files from .gitignore
      run: sed -n '/# Generated files/q;p' .gitignore > .gitignore

    - name: Upload to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/
